### PR TITLE
Added CircleCI configuration

### PR DESCRIPTION
**Pull request by pchakraborty**

### CODE REVIEW

**Comment by mathomp4** [comment]
Ha! This is going to be fun. I need to figure out how to get Circle as a dependency at which point both Circle and Travis will try to build with every push. :+1: 

I'm thinking I might need to disable the Travis-on-every-push...

**Comment by pchakraborty** [comment]
I tried to add GEOagcm project in circleci, but it tells me to contact the admin.

**Comment by mathomp4** [comment]
> I tried to add GEOagcm project in circleci, but it tells me to contact the admin.

What's that? On circleci itself? Or when you tried to merge here? And should I merge in the pull request?

**Comment by pchakraborty** [comment]
Yes, on circleci.com. Here is a screenshot:

screen shot 2018-03-12 at 10 36 35 am

**Comment by mathomp4** [comment]
Huh. Well, let me log into CircleCI. I guess it needs some permission only the owner can provide?

...

...

Well, I clicked some buttons. Let me know if it helps? It seems to have triggered a build.

**Comment by mathomp4** [comment]
Merging the pull request to see if that is needed

**Comment by pchakraborty** [comment]
It worked!

**Pull request merged**
